# One named division of the corridor.
#
# Named after the unit TT Games use: a level divides into lettered sub-areas
# (A, B, D1, E, G), and camera files, music zones and level data all key off
# that SAME division rather than each system inventing its own boundaries.
# See Docs/TT_ENGINE_NOTES.md section 8.
class_name SubArea
extends RefCounted

# PROCEDURAL areas are generated by the streamer. AUTHORED areas are placed by
# hand and are never touched by procedural population - that reservation used
# to be open-coded arithmetic in the streamer with its own magic numbers.
enum Kind { PROCEDURAL, AUTHORED }

# The three states TT's music config uses, in their order of escalation:
# ambience only, a quiet bed, and the action variant.
enum Intensity { AMBIENT, QUIET, ACTION }

var id: String = ""
var index: int = 0
var kind: int = Kind.PROCEDURAL
var z0: float = 0.0
var depth: float = 0.0

# Structures born in this area. The area owns them for lifecycle purposes; a
# structure that has WANDERED out (thrown by the funnel) is re-homed on
# retirement rather than freed early. See AreaMap.retire_behind.
var structures: Array = []

# ---- framing hints -------------------------------------------------------
# Metres added to the automatic camera's distance and height while the subject
# is inside this area. Zero on procedural areas: the camera is automatic by
# default and hand-authored only where it matters, which is how the LEGO games
# do it - only some sub-areas ship a camera file at all.
var cam_back_bias: float = 0.0
var cam_height_bias: float = 0.0
# The blend distance outside the area over which the hint fades in and out.
# TT call this the camera's range of effect; without it the framing snaps at
# the boundary, which reads as a glitch rather than as direction.
var cam_range: float = 18.0

var intensity: int = Intensity.AMBIENT


func z1() -> float:
	return z0 + depth


func contains_z(z: float) -> bool:
	return z >= z0 and z < z1()


# 0 outside the range of effect, 1 anywhere inside the area, smooth between.
func framing_weight(z: float) -> float:
	if contains_z(z):
		return 1.0
	if cam_range <= 0.0:
		return 0.0
	var d: float = (z0 - z) if z < z0 else (z - z1())
	return clampf(1.0 - d / cam_range, 0.0, 1.0)


func describe() -> String:
	return "%s[%.0f..%.0f]%s" % [id, z0, z1(),
		"*" if kind == Kind.AUTHORED else ""]
